export enum ProjectEventType {
    PROJECT_CREATED = 'PROJECT_CREATED',
    USER_APPLIED = 'USER_APPLIED',
    USER_JOINED = 'USER_JOINED',
    USER_LEFT = 'USER_LEFT',
    MEMBER_REMOVED = 'MEMBER_REMOVED',
    PROJECT_CLAIMED = 'PROJECT_CLAIMED',
    STATUS_CHANGED = 'STATUS_CHANGED',
    PROJECT_IMPORTED = 'PROJECT_IMPORTED'
}
